### ISSUE TITLE
[Umbrella] MySQL Protocol Frontend

### ISSUE THREAD

**Issue by pan3793** [apache/incubator-kyuubi#1219]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

Implement MySQL Protocol Frontend service in `kyuubi-server` to support connect Kyuubi by MySQL client, e.g. `mysql` CLI, MySQL JDBC driver.

![image](https://user-images.githubusercontent.com/26535726/139849526-f28eb7ae-05e9-436e-a3cc-b9efd09bca0c.png)

### Task list

- [ ] #1348
- [ ] #1358
- [ ] #1395
- [ ] #1376

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by timothy65535** [comment]
Nice idea!!
