### ISSUE TITLE
[Umbrella][KPIP-2] Support FlinkSQL Engine

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#1322]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

- [X] The detailed proposal is [here](https://github.com/apache/incubator-kyuubi/discussions/1132). #1132 

### Task list

- [x] #1323 @yanghua 
- [x] #1329 @yanghua  
- [x] #1340 @yanghua 
- [x] #1386 @yanghua 
- [x] #1492 @yanghua  
- [x] #1503 @yanghua 
- [x] #1525 @yanghua 
- [x] #1542 @yanghua 
- [x] #1555 @yanghua  
- [x] #1578 @yanghua 
- [x] #1579 @yanghua 
- [x] #1587 @pan3793 
- [x] #1629 @pan3793  
- [x] #1643 @SteNicholas
- [x] #1645 @SteNicholas
- [x] #1646 @xifeng 
- [x] #1647 @yanghua
- [x] #1648 @SteNicholas
- [x] #1663
- [x] #1665 @yanghua 
- [x] #1679 @link3280 
- [x] #1681 @link3280 
- [x] #1685 @SteNicholas
- [x] #1687 @yanghua 
- [x] #1705 @yanghua 
- [x] #1704 @link3280 
- [x] #1709 @yanghua 
- [x] #1774 @yanghua 
- [x] #1787 @yanghua
- [x] #1778 @link3280 
- [x] #1814 @SteNicholas
- [x] #1819 @SteNicholas
- [x] #1825 @link3280 
- [x] #1829 @SteNicholas
- [x] #1838 @link3280 
- [x] #1839 @link3280 
- [x] #1867 @SteNicholas
- [x] #1883 @link3280 
- [x] #1919 @SteNicholas 
- [x] #1926 @yanghua 
- [x] #1866 @deadwind4 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by ulysses-you** [comment]
great work

**Comment by SteNicholas** [comment]
@yanghua @yaooqinn , any other subtasks? In above task list, the tasks are completed.

**Comment by pan3793** [comment]
> In above task list, the tasks are completed.

Not yet. The current implementation should be considered as a PoC version, and we do find some disadvantages of this approach, the next step is to investigate Flink `application` mode.

**Comment by yaooqinn** [comment]
> @yanghua @yaooqinn , any other subtasks? In above task list, the tasks are completed.

@yanghua could you add more uncompleted tasks to the list, like metaapis, operation logs etc

**Comment by yanghua** [comment]
> > @yanghua @yaooqinn , any other subtasks? In above task list, the tasks are completed.
> 
> @yanghua could you add more uncompleted tasks to the list, like metaapis, operation logs etc

fine, there are still many operations that did not implement @SteNicholas . Will file more subtask issues.

**Comment by SteNicholas** [comment]
@yanghua @yaooqinn @pan3793 , thanks for your reply. IMO, the current implementation doesn't affect the interface definition. Therefore, I could start to add the operations based on the current implementation. Right?

**Comment by yanghua** [comment]
> @yanghua @yaooqinn @pan3793 , thanks for your reply. IMO, the current implementation doesn't affect the interface definition. Therefore, I could start to add the operations based on the current implementation. Right?

yes, brother

**Comment by link3280** [comment]
@yanghua Thanks for your great work! The proposal seems to be sort of lagged behind. It would be great if we can update it as well. I'll be happy to take some tasks if possible.

**Comment by yanghua** [comment]
> @yanghua Thanks for your great work! The proposal seems to be sort of lagged behind. It would be great if we can update it as well. I'll be happy to take some tasks if possible.

You are right. The design doc does not match the implementation. Will update it later.

**Comment by link3280** [comment]
@yanghua I noticed that `ExecuteStatement` of Flink engine now supports QueryOperation only. May I add a subtask and create a PR to fix this?

**Comment by yanghua** [comment]
> ExecuteStatement

Absolutely yes, welcome!

**Comment by yanghua** [comment]
@SteNicholas Ping me if you create new subtasks.

**Comment by yaooqinn** [comment]
retargeting improvement PR to v1.6 and collection to another ticket https://github.com/apache/incubator-kyuubi/issues/2100 to track

**Comment by pan3793** [comment]
Thanks to all contributors who participated, I'm going to close this ticket, and please go ahead in #2100
