### ISSUE TITLE
[Umbrella] Add Support for executing Scala/Spark Scripts

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#1489]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

Add support for running scala/spark code snippet through all types of Kyuubi-supported clients.

### Task list

- [ ] #1490 Introduce the basic framework for running scala
- [ ] #1498 Support scala operation logging
- [ ] #1499
- [x] #1504 
- [ ] #XXX Support scala operation events
- [ ] #XXX Improve scala operation results exchanging 
- [ ] #XXX Add documentation for scala operation

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by zhenjiaguo** [comment]
LGTM
