### ISSUE TITLE
[Umbrella] Add more metric in kyuubi server

### ISSUE THREAD

**Issue by zhenjiaguo** [apache/incubator-kyuubi#1703]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

According to discussions #1671. I will try to add more metric in kyuubi server.

### Task list

- [x] #1696 
- [x] #1697
- [x] #1698 
- [x] #1699 
- [x] ~~#1700~~
- [x] ~~#1701~~
- [x] ~~#1702~~
- [x] #1914 

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
thanks @zhenjiaguo

**Comment by yaooqinn** [comment]
can you check this flaky test?

```
BackendServiceTimeMetricSuite:
- backend service method time metric test *** FAILED ***
  java.io.FileNotFoundException: /home/runner/work/incubator-kyuubi/incubator-kyuubi/kyuubi-server/target/tmp/kyuubi-9fba7112-636f-4d96-a867-b0f746995bed/report.json (No such file or directory)
  at java.io.FileInputStream.open0(Native Method)
  at java.io.FileInputStream.open(FileInputStream.java:195)
  at java.io.FileInputStream.<init>(FileInputStream.java:138)
  at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1029)
  at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3076)
  at org.apache.kyuubi.server.BackendServiceTimeMetricSuite.$anonfun$new$2(BackendServiceTimeMetricSuite.scala:60)
  at org.apache.kyuubi.server.BackendServiceTimeMetricSuite.$anonfun$new$2$adapted(BackendServiceTimeMetricSuite.scala:45)
  at org.apache.kyuubi.operation.JDBCTestHelper.$anonfun$withMultipleConnectionJdbcStatement$3(JDBCTestHelper.scala:60)
  at org.apache.kyuubi.operation.JDBCTestHelper.$anonfun$withMultipleConnectionJdbcStatement$3$adapted(JDBCTestHelper.scala:60)
  at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  ...
```

**Comment by zhenjiaguo** [comment]
> can you check this flaky test?
> 
> ```
> BackendServiceTimeMetricSuite:
> - backend service method time metric test *** FAILED ***
>   java.io.FileNotFoundException: /home/runner/work/incubator-kyuubi/incubator-kyuubi/kyuubi-server/target/tmp/kyuubi-9fba7112-636f-4d96-a867-b0f746995bed/report.json (No such file or directory)
>   at java.io.FileInputStream.open0(Native Method)
>   at java.io.FileInputStream.open(FileInputStream.java:195)
>   at java.io.FileInputStream.<init>(FileInputStream.java:138)
>   at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1029)
>   at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3076)
>   at org.apache.kyuubi.server.BackendServiceTimeMetricSuite.$anonfun$new$2(BackendServiceTimeMetricSuite.scala:60)
>   at org.apache.kyuubi.server.BackendServiceTimeMetricSuite.$anonfun$new$2$adapted(BackendServiceTimeMetricSuite.scala:45)
>   at org.apache.kyuubi.operation.JDBCTestHelper.$anonfun$withMultipleConnectionJdbcStatement$3(JDBCTestHelper.scala:60)
>   at org.apache.kyuubi.operation.JDBCTestHelper.$anonfun$withMultipleConnectionJdbcStatement$3$adapted(JDBCTestHelper.scala:60)
>   at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
>   ...
> ```

This test set `metrics.json.interval` is `100ms`, that means every `100ms` will generate a JSON reporters file in the path `java.io.tmpdir + kyuubi + UUID.randomUUID()` that we define in test. Every query in this test, will wait `111ms` to wait JSON file generate or update.

That seems that JSON file is not generate after we query `111ms`.

I never meet this error before. Can you give me more information? Or you can try to sleep more than `111ms` after query.
