### ISSUE TITLE
[Umbrella] Flaky Tests Governance

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#1733]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

This umbrella issue is used to collect and govern flaky tests.

### Task list

- [ ] #1732 @yanghua 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
