### ISSUE TITLE
[Umbrella] Add Hive Backend Engine Support

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2010]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

Add Hive Backend Engine Support

Support a lightweight hive engine which has some advantages over hiveserver2
- separate engine/process to the Kyuubi-multi-tenancy framework for better stability, without having a heavy server
- more engines introduced in Kyuubi, Hive may be aged but still widely used
- also good for us to do some cross verifications for spark/flink etc with a stable hive.

Implementing a hive engine is very easy, we
- At the engine-side, use our owner FE for RPCs and BE for scheduling operations, the operations can be easily delegated to hive ones
- At the server-side, we add a new type,  a progress launcher, and schedule them like others

### Task list

- Engine Runtime
  - [x] #2011
  - [x] #2014
  - [x] #2015
  - [x] #2016
  - [x] #2017
  - [x] #2018
  - [x] #2019
  - [x] #2033
  - [x] #2034
  - [x] #2021
  - [x] #2020
  - [x] #2032
  - [x] #2297
  - [x] #2330
  - [x] #2360

- Server Integration
  - [x] #2022
  - [x] #2023
  - [x] #2024
  - [x] #2025
  - [ ] #2026
  - [ ] #2027
  - [x] #2604
- Documentation
    - #2326 

- Others
   - [x] #2028
   - [x] #2029
   - [x] #2035
   - [ ] Help testing with different environments
   - [x] #2351
   - [x] #2426
   - [x] #2490
   - [x] #2558
  
 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by SteNicholas** [comment]
@yaooqinn, I have interest to support Hive backend engine. Could you please firstly assign the `engine Runtime` module tickets to me?

**Comment by yaooqinn** [comment]
@SteNicholas, thanks for interesting in this feature. You need to leave a comment there, so I can find you in the dropbox of assignees. Or you just simply leave 'I am working on this' and start work.

**Comment by KenjiFujima** [comment]
@yaooqinn, could this issue be closed and create another issue for improvement?
