### ISSUE TITLE
[Umbrella] Kyuubi server web ui

### ISSUE THREAD

**Issue by cfmcgrady** [apache/incubator-kyuubi#2069]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

Add Kyuubi server web ui, that displays useful information about the server, including `Environment/Sessions/Operations/Metrics/Thread dump/REST API/Documentation`.

### Task list

- [x] #2061
- [ ]  #2072

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by cfmcgrady** [comment]
cc @yaooqinn

**Comment by yaooqinn** [comment]
thanks @cfmcgrady

**Comment by pan3793** [comment]
close and in favor #3248
