### ISSUE TITLE
[Umbrella] Manage test failures with kyuubi spark nightly build

### ISSUE THREAD

**Issue by yaooqinn** [apache/incubator-kyuubi#2176]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

We have nightly Github action[1] to check compatibility with the Spark master branch as some breaking changes might be introduced upstream.

It's a good way for new contributors and those who want to get familiar with Kyuubi and Spark.

Please help us to fix those test failures, compile failures, etc.

[1] https://github.com/apache/incubator-kyuubi/actions/workflows/nightly.yml 

### Task list

- [x] #2184 
- [x] #2185
- [x] #2186 
- [x] #2187 
- [x] #2188 
- [x] #2189 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Nick-0723** [comment]
Hi, I want to try it

**Comment by pan3793** [comment]
@Nick-0723 thanks, assigned this ticket to you

**Comment by yaooqinn** [comment]
you may need to fix test failures case by case. you can create subtasks for them and get help from the community if you need it.

**Comment by Nick-0723** [comment]
> 

- [ ] operation listener *** FAILED ***
- [ ] execute statement - select interval *** FAILED ***
- [ ] execute simple scala code *** FAILED ***
- [ ] deregister exception ttl test *** FAILED ***
- [ ] Scheduler pool *** FAILED ***
- [ ] deregister when meeting specified exception *** FAILED ***

I fixed 1, 3, 5 should I submit a pr first ？

**Comment by yaooqinn** [comment]
that's great，better to submit case by case if appropriate

**Comment by Nick-0723** [comment]
I don't know how to fix this iusse https://github.com/apache/incubator-kyuubi/issues/2186

**Comment by yaooqinn** [comment]
> I don't know how to fix this iusse #2186

Spark adds new interval types, we need to support them. FYI, https://spark.apache.org/docs/latest/sql-ref-datatypes.html

**Comment by Nick-0723** [comment]
> > I don't know how to fix this iusse #2186
> 
> Spark adds new interval types, we need to support them. FYI, https://spark.apache.org/docs/latest/sql-ref-datatypes.html

thanks

**Comment by Nick-0723** [comment]
I found this feature support is trackd in #1250 , should I just fix it in the test case ?  skip version spark 3.3
```scala
  test("execute statement - select interval") {
    // FIXME: [KYUUBI #1250]
    assume(SPARK_ENGINE_MAJOR_MINOR_VERSION !== ((3, 2)))
    withJdbcStatement() { statement =>
      val resultSet = statement.executeQuery("SELECT interval '1' day AS col")
      assert(resultSet.next())
      assert(resultSet.getString("col") === "1 days")
      assert(resultSet.getMetaData.getColumnType(1) === java.sql.Types.VARCHAR)
      val metaData = resultSet.getMetaData
      assert(metaData.getPrecision(1) === Int.MaxValue)
      assert(metaData.getScale(1) === 0)
    }
  }
```

**Comment by Nick-0723** [comment]
> > I don't know how to fix this iusse #2186
> 
> Spark adds new interval types, we need to support them. FYI, https://spark.apache.org/docs/latest/sql-ref-datatypes.html

I found this feature support is trackd in https://github.com/apache/incubator-kyuubi/issues/1250 , should I just fix it in the test case ? skip version spark 3.3

```scala
  test("execute statement - select interval") {
    // FIXME: [KYUUBI #1250]
    assume(SPARK_ENGINE_MAJOR_MINOR_VERSION !== ((3, 2)))
    withJdbcStatement() { statement =>
      val resultSet = statement.executeQuery("SELECT interval '1' day AS col")
      assert(resultSet.next())
      assert(resultSet.getString("col") === "1 days")
      assert(resultSet.getMetaData.getColumnType(1) === java.sql.Types.VARCHAR)
      val metaData = resultSet.getMetaData
      assert(metaData.getPrecision(1) === Int.MaxValue)
      assert(metaData.getScale(1) === 0)
    }
  }
```

**Comment by yaooqinn** [comment]
Do not skip this, otherwise, we will maybe `never` fix it

**Comment by Nick-0723** [comment]
> 

👌

**Comment by yaooqinn** [comment]
@Nick-0723, If you have no idea how to fix this, shall I create an example for you? then, you can support other newly added spark data types just like I do?

**Comment by Nick-0723** [comment]
> @Nick-0723, If you have no idea how to fix this, shall I create an example for you? then, you can support other newly added spark data types just like I do?

Thank you, I would love it, it's a very good learning opportunity

**Comment by yaooqinn** [comment]
hi @Nick-0723 ，can you check whether any test failures still exists in ci？otherwise，we can close this，and you can make PRs to support other datatypes

**Comment by Nick-0723** [comment]
> 

I tested it locally and there is no failures. After today's nightly build is over, I will close this issue. The other two datatypes I'm looking at, may take a while，I'll create a issue to track it

**Comment by yaooqinn** [comment]
thanks @Nick-0723 for the effort

**Comment by Nick-0723** [comment]
Today's nightly build succeded, but I can't close this issue 😢

**Comment by yaooqinn** [comment]
thanks @Nick-0723, I'll close
