### ISSUE TITLE
[Umbrella] Support Chinese Documents and Website for Kyuubi

### ISSUE THREAD

**Issue by zhenjiaguo** [apache/incubator-kyuubi#2561]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

# Motivation
In order to better develop the kyuubi community, it would be helpful to support the Chinese website and documents.
# Implementation
## Chinese website
Kyuubi website is base on Hugo. Hugo is support multi-language, detail see [Multilingual Mode](https://gohugo.io/content-management/multilingual/).
Translation implements by two ways:
1. [Translation by content directory](https://gohugo.io/content-management/multilingual/#translation-by-content-directory) for `markdown` files. This way is set different directories for different languages. For instance, `src/en` for English markdown file and `src/zh` for Chinese markdown files.
2. [Translation of Strings](https://gohugo.io/content-management/multilingual/#query-basic-translation) for `HTML` files. This way is to define an id and then translation in the corresponding file, like `i18n/zh.toml` for Chinese and `i18n/en.toml` for English.

## Chinese document
Kyuubi document is build by Sphinx independent.I find It is not easy to combine two languages document together.

So my method is to put the different languages documents into different folders and compile them separately. And then link the different language documents to the different language Kyuubi website.

If you have a better way to do it, please let me know.

### Task list

- [ ] #2563 
- [ ] Translation document to Chinese
- [ ] Link to the corresponding document

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!
