### ISSUE TITLE
[Umbrella][KPIP-5] Introduce Kyuubi Web UI

### ISSUE THREAD

**Issue by yanghua** [apache/incubator-kyuubi#2652]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

The proposal is here. #2651 

### Task list

- [ ]

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!
