### ISSUE TITLE
[Umbrella] Improve kyuubi official documentation

### ISSUE THREAD

**Issue by lxorc** [apache/incubator-kyuubi#3005]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

Improve official documents, improve community activity and lower the threshold for beginners

### Task list

- [ ] improve quick start pages
- [ ] Correct spelling errors and optimizations in 'Building Kyuubi Documentation'

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!
