### ISSUE TITLE
[Umbrella] Spark-3.3 lakehouses support

### ISSUE THREAD

**Issue by cfmcgrady** [apache/incubator-kyuubi#3328]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

Set spark 3.3 as default w.r.t all lakehouses supported for unit tests.

### Task list

- [x] #3263 
- [x] #3050 
- [x] #3244 
### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
👍
