### ISSUE TITLE
[Umbrella] [FEATURE] Support Hive V2 DataSource in Kyuubi

### ISSUE THREAD

**Issue by yikf** [apache/incubator-kyuubi#3365]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

Hey everyone,

In a modern database architecture, users may have a strong need for federated queries. Since there are a large number of Hive warehouse in the history database, we tried to implement the Hive V2 Datasource based on Spark Datasource V2 to meet this need. for the discussion, see :https://lists.apache.org/thread/fq8ywr58rzf9bycflj1q4fl1xyz2rq2w

### Task list

To do this, we have some subtask as follow:

- [x] #3259 
- [x] #3366 
- [x] #3378 
- [x] #3437
- [x] #3531
- [x] #3464
- [x] #3529

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yaooqinn** [comment]
completed？

**Comment by yaooqinn** [comment]
1.6？

**Comment by Yikf** [comment]
It should be 1.7
