### ISSUE TITLE
[Subtask] [Authz] extend `PrivilegeObject` and`AccessResource` to support catalog

### ISSUE THREAD

**Issue by bowenliang123** [apache/incubator-kyuubi#3605]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

add catalog support in `PrivilegeObject`,`AccessRequest` and `RangerAccessRequest`, and with #3594 initialed ranger plugin for catalog names.

### Parent issue

#3586 

### Are you willing to submit PR?

- [X] Yes. I can submit a PR independently to improve.
- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.
