### ISSUE TITLE
[Umbrella] RangerSparkExtension support {OWNER} variable defined in Ranger Policy

### ISSUE THREAD

**Issue by zhouyifan279** [apache/incubator-kyuubi#3607]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

Currently, if user does not have insert permission of all tables in a database, AccessControlException will be throw when user
insert into a newly created table.

RangerBasePlugin uses {OWNER} variable to remove this limitation:

At Ranger Admim side, set {OWNER} variable in Ranger Policy `Users` field.
![image](https://user-images.githubusercontent.com/88070094/196728037-d173f5c3-997e-402a-8d91-1471e2a39914.png)

At Ranger Plugin side, due to the above policy, current user gets the specified permissions of any table he creates(owns).
Ranger Plugin deals with  {OWNER} variable in `org.apache.ranger.plugin.policyevaluator.RangerDefaultPolicyItemEvaluator#matchUserGroupAndOwner`:
![image](https://user-images.githubusercontent.com/88070094/196723898-ed11c8bd-c08f-4190-863e-4a0c3797de21.png)

Some works need to be done to support this feature in  Kyuubi RangerSparkExtension.

### Task list

- [x] #3608
- [ ] ~~#Get table owner by TableIdentifier~~
- [x] #3666
- [x] #3672
- [ ] ~~#Cache table info to reduce Catalog method invocations~~
- [x] #3675

### Are you willing to submit PR?

- [X] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.

**Comment by bowenliang123** [comment]
This would be helpful for applying {OWNER} to policies.

But two problem to consider about this ,
1. is it investigating the owner for all tables even with no {OWNER} rules on them?  This will cause a heavy cpu time to fetch these information, and additional cache will leave more memory footprints to it .
2. what is the proper caching and evicting strategy for caching table owners ? LTT or max cache counts will introducing worries for missed queries, whether they will be fetched again which could causing more action and load in 1.

**Comment by bowenliang123** [comment]
Thanks for the investigation and explanation. Since the owner name is carried in `CatalogTable` in V1 and in `table` in V2Realtion, it's alright to use them without extra fetching action. And as of now we don't have to cache them in runtime, that's good enough for concrete implementation.
@zhouyifan279
