### ISSUE TITLE
[Subtask] AdminResources rest api support to list current engines

### ISSUE THREAD

**Issue by lightning-L** [apache/incubator-kyuubi#3626]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the subtask

list engine api

### Parent issue

https://github.com/apache/incubator-kyuubi/issues/3554

### Are you willing to submit PR?

- [ ] Yes. I can submit a PR independently to improve.
- [X] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.
