### ISSUE TITLE
[Umbrella] Make table owner defaults to kyuubi.session.user when create table

### ISSUE THREAD

**Issue by zhouyifan279** [apache/incubator-kyuubi#3687]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### Search before asking

- [X] I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues) and found no similar issues.

### Describe the proposal

When run Kyuubi Spark SQL Engine in GROUP or SERVER mode, newly-created table's owner defaults to engine launch user.
However, some people may want to set table owner to Kyuubi session user.

We should support this behavior in KyuubiSparkExtension and provide a conf to enable/disable it.

### Task list

- [] #Set table owner to Kyuubi session user for table-creation Command having CatalogTable field
- [] #Set table owner to Kyuubi session user for table-creation Command not having CatalogTable field

### Are you willing to submit PR?

- [X] Yes. I can submit a PR independently to improve.
- [ ] Yes. I would be willing to submit a PR with guidance from the Kyuubi community to improve.
- [ ] No. I cannot submit a PR at this time.
